### ISSUE TITLE
option to not recast parameters in energy pair functions

### ISSUE THREAD

**Issue by cpgoodri** [google/jax-md#109]
In functions such as `soft_sphere_pair`, parameters (e.g. `sigma`, `epsilon`, `alpha`) are explicitly cast to np.float32. However, sometimes it is actually important to keep some parameters at double precision. It would be nice if there was an option that would direct `soft_sphere_pair` to recast the parameters. Something like
```
energy_fn = energy.soft_sphere_pair(displacement, sigma=jnp.array([1.0],dtype=jnp.float64), dont_recast=True)
```

Is there a reason not to do this?

**Comment by sschoenholz** [comment]
This is a great idea! As of commit 52472f34404ec09437d4314806c8a7a452e49cca we now don't downcast if parameters are explicitly passed as float64. Feel free to reopen if this doesn't work as it should.
