### ISSUE TITLE
Bug/Documentation problem with **kwargs for simulate/minimize methods.

### ISSUE THREAD

**Issue by MaxiLechner** [google/jax-md#112]
When passing a wrapped function to simulate.brownian I get an " unexpected keyword argument 't' " error. This is easily resolved by passing through **kwargs, but I'd prefer if this was not necessary as this is not documented and  only needed in some cases.

## example

import jax.numpy as jnp

from jax.config import config
config.update("jax_enable_x64", True)

from jax import random
from jax_md import space, energy, simulate

displacement, shift = space.periodic(side_length)
energy_fn = energy.soft_sphere_pair(displacement)

### This does not work
no_keywords_fn = lambda R: energy_fn(R)

init, apply = simulate.brownian(no_keywords_fn, shift, dt=0.00001, T_schedule=1.0, gamma=0.1)
key, split = random.split(key)
state = init(split, R)
apply(state)

### This does work
keywords_fn = lambda R, **kwargs: energy_fn(R,**kwargs)

init, apply = simulate.brownian(keywords_fn, shift, dt=0.00001, T_schedule=1.0, gamma=0.1)
key, split = random.split(key)
state = init(split, R)
apply(state)

This is not an issue for nvt_nose_hoover and for minimize.fire_decent.

The same issue also appears for nve. 

And for nvt_langevin this issue appears for both init and apply.

**Comment by sschoenholz** [comment]
Thanks for raising this issue! Sorry for the delay, I was taking some time off over the holidays. The requirement of passing `t` as a keyword argument should be removed from all simulation / minimization functions as of c55ec95999331844a72a1e1a3a3009276c60a098. Let me know if you run into any issues here or if I missed anything.

**Comment by MaxiLechner** [comment]
Great thanks!
