### ISSUE TITLE
Possible improvements to neighbor lists

### ISSUE THREAD

**Issue by cpgoodri** [google/jax-md#117]
A few minor suggestions to help improve the clarity/performance of neighbor lists:

1. Split `neighbor_fn` (the returned function of `partition.neighbor_list`) into two, rather than having the two different use cases where only one case is compatible with jit/grad. So, for example:
```
neighbor_fn, energy_fn = lennard_jones_neighbor_list(displacement, box_size)

#construct the neighbor list
nbrs = neighbor_fn(R)

#update the neighbor list
nbrs = neighbor_fn(R, nbrs)
```
would become
```
(construct_neighbor_fn, update_neighbor_fn), energy_fn = lennard_jones_neighbor_list(displacement, box_size)

#construct the neighbor list
nbrs = construct_neighbor_fn(R)

#update the neighbor list
nbrs = update_neighbor_fn(R, nbrs)
```
It would then be easier to communicate that `update_neighbor_fn `can be included with `jax` transformation, but `construct_neighbor_fn` cannot.

2. Pass kwargs through the neighbor list convenience functions in energy.py. Unless I'm missing something, there currently is not a way to change, e.g., `capacity_multiplier` using these convenience functions. 

3. I know this has come up in the past, but I forget the rationale behind scaling `dr_threshold`, e.g.:
https://github.com/google/jax-md/blob/c55ec95999331844a72a1e1a3a3009276c60a098/jax_md/energy.py#L223
This is done for some of the potentials (soft_sphere, LJ) but not others (morse, bks). My feeling is that physically `dr_threshold` is a buffer for how far particles can move before the neighbor lists have to be recomputed, but big particles don't typically move faster than small particles (depending on the dynamics/potentials). I'm all for coming up with intelligent heuristics for what the optimum `dr_threshold` should be, its not clear that this is the right heuristic. But I'm happy to be wrong.

**Comment by sschoenholz** [comment]
I took a pass at some API improvements in #154. However, some other things (changing the capacity multiplier and the semantics for `dr_threshold`) didn't make it in yet. I do think they are good suggestions and I hope to add them in next week. At some point (hopefully soon-ish) there will also be another round of neighbor list improvements that target better compatibility with `periodic_general` and `npt` simulations.

For reference, the idea behind scaling `dr_threshold` was that `max(sigma)` sort of sets the units for the problem. However, I also agree that there are use cases where that is not true and probably keeping `dr_threshold` a scale free constant might be better in practice.

**Comment by sschoenholz** [comment]
Okay! Not quite a week, but as of version 0.1.22 `dr_threshold` no longer scales with `max(sigma)` and the neighbor list arguments have been threaded through all of the appropriate energy functions.

Let me know if you run into any issues! Thanks for the feedback.

**Comment by cpgoodri** [comment]
Awesome! I'll let you know if we run into any issues :)
