### ISSUE TITLE
Update customizing potentials notebook for kT change

### ISSUE THREAD

**Issue by cwbeitel** [google/jax-md#120]
Looks like https://github.com/google/jax-md/commit/c55ec95999331844a72a1e1a3a3009276c60a098 may have broken the [customizing potentials notebook](https://github.com/google/jax-md/blob/master/notebooks/customizing_potentials_cookbook.ipynb). E.g. in various places, `simulate.brownian` calls need changes of parameterization from `T_schedule=1.0` to `kT=1.0`.

I'll just go ahead and submit a patch and maybe a test to verify notebooks run without error?

Thanks a lot for this work, @sschoenholz and others, it's been really interesting to learn about.

**Comment by sschoenholz** [comment]
Thanks for trying out jax md and for quick identification of the issue!
