### ISSUE TITLE
Incorrect behaviour of Langevin thermostat

### ISSUE THREAD

**Issue by S-Thaler** [google/jax-md#124]
Hi, 
thanks for launching this great project!

I think I encountered a bug in the Langevin thermostat.
As a minimal example, I created a box of ideal gas particles trapped in a well-potential.
The Nose-Hoover simulator produces the expected particle density of the well, while the Langevin simulator incorrectly predicts 2 peaks. I changed gamma values over a large range with similar results, so I don't think it's just a funny parameter choice.

Any insights are highly welcome.

```python
import jax.numpy as jnp
from jax import random, vmap, jit, lax
from jax_md import simulate, space
import matplotlib.pyplot as plt


def plot_1d_over_x(x, z, x_label=None, y_label=None, title=None):
    fig, ax = plt.subplots()
    ax.plot(x, z)
    ax.set_title(title)
    ax.set_xlabel(x_label)
    ax.set_ylabel(y_label)
    plt.show()


N = 1000
dt = 1.e-3
kbT = 1.
mass = 1.
resolution = 100
box = jnp.array([1.])

n_steps_per_printout = 100
snapshots_dumped = 10000
snapshots_kept = 10000


@vmap
def analytic_well(x):
    well = 2000 * (x - 0.5)**6
    return kbT * well


def analytic_energy_fn(R, t=0):
    # the dummy value of t is necessary to avoid error in langevin initialisation
    energies = analytic_well(R)
    return jnp.sum(energies)


x_vals = jnp.linspace(0., box, resolution)
analytic_potential_vals = analytic_well(x_vals)
plot_1d_over_x(x_vals, analytic_potential_vals, x_label='x', y_label='U / kbT')

_, shift = space.periodic(box)
key = random.PRNGKey(0)
position_key, simuation_key = random.split(key, 2)
R_init = box * random.uniform(position_key, (N, 1))


init, apply = simulate.nvt_nose_hoover(analytic_energy_fn, shift, dt, kbT)  # works
# init, apply = simulate.nvt_langevin(analytic_energy_fn, shift, dt, kbT, gamma=0.1)  # incorrect results

init_state = init(simuation_key, R_init)
do_step = lambda state, t: (apply(state), ())


@jit
def run_to_printout(start_state, dummy_carry):
    printout_state, _ = lax.scan(do_step, start_state, xs=jnp.arange(n_steps_per_printout))
    return printout_state, printout_state


state, _ = lax.scan(run_to_printout, init_state, xs=jnp.arange(snapshots_dumped))  # equilibration
_, traj = lax.scan(run_to_printout, state, xs=jnp.arange(snapshots_kept))  # sample

hist, _ = jnp.histogram(traj.position, bins=resolution)
plot_1d_over_x(x_vals, hist, x_label='x', y_label='Frequency')

```

![Potential](https://user-images.githubusercontent.com/48491432/107806636-65afa100-6d67-11eb-821d-78ff4830ec41.png)
![Nose_Hoover](https://user-images.githubusercontent.com/48491432/107801438-5bd66f80-6d60-11eb-9623-4d0383ecee5d.png)
![Langevin](https://user-images.githubusercontent.com/48491432/107801451-60028d00-6d60-11eb-98e8-2861f2303bb5.png)

**Comment by sschoenholz** [comment]
Thanks a lot for reporting this bug and for the clean repro! It turns out there was an extra term proportional to force that I missed in the Langevin thermostat. It's fixed as of https://github.com/google/jax-md/commit/e8ca65aea69182ef1170063c49e6e8ef5a9559b6.

Don't hesitate to let me know if you find any other problems!

**Comment by S-Thaler** [comment]
That did the trick. Thanks for the quick fix!
