### ISSUE TITLE
Possible bug in maybe_downcast()

### ISSUE THREAD

**Issue by cpgoodri** [google/jax-md#128]
https://github.com/google/jax-md/blob/82bd5d3423b4e9a008540a50c16252790be66f3d/jax_md/util.py#L77

see repo: https://pastebin.com/EhqHetFv

I thought I had checked this a long time ago, but I guess I didn't.

**Comment by sschoenholz** [comment]
Thanks for reporting this! Should be fixed (along with a test) as of eeba3987da0df39c35f5b7b502503335e83c6132.
