### ISSUE TITLE
Add lax.stop_gradient calls in partition.neighbor_list?

### ISSUE THREAD

**Issue by MaxiLechner** [google/jax-md#129]
Is was wondering if there were any downsides to call ```lax.stop_gradient``` on ```box_size```, ```r_cutoff``` and ```dr_threshold``` within ```partition.neighbor_list```? This way it would always be possible to differentiate through a minimization/dynamics routine capable of building new neighbor_lists.

**Comment by sschoenholz** [comment]
Good idea! Added in 6c60d5b589addeae62cf1002aa714293cf5f35a0.
