### ISSUE TITLE
Feature Request: Verlet lists

### ISSUE THREAD

**Issue by cpgoodri** [google/jax-md#13]
This is not something that I need now, but it is almost certainly a feature that you'll eventually want to include. The standard (e.g. in LAMMPS and HOOMD) for fast neighbor detection is to use a combination of cell lists (which you already have) and Verlet lists, i.e. use cell lists to create and periodically update Verlet lists. I've noticed a non-negligible speedup compared to just cell lists in my own code, and for people who really care about these things, I think it's pretty important.

I would be happy to chat more about this.

**Comment by sschoenholz** [comment]
Added a version of this in 65d0ecf8fd8cbbd55b5c21955b780a8aa13bd074.
