### ISSUE TITLE
High memory usage for moderately large simulation

### ISSUE THREAD

**Issue by aniquetahir** [google/jax-md#137]
Hi, 

I wanted to use Jax MD to aid in positioning nodes in a graph. I am not familiar with the size of datasets that MD community generally uses. However, just trying to simulate 40k nodes consumes all memory on a V100. I have tried neighbour_list to assuage the issue to no avail. Is there any way to make this work or any plans for supporting more particles?

Best,
Anique

**Comment by sschoenholz** [comment]
Hey @aniquetahir, thanks for looking into JAX MD. I would think that 40k nodes should be no problem on a V100 with neighbor lists (depending on how many nodes each node neighbored). Do you have some example code that fails so that I can take a look.

**Comment by aniquetahir** [comment]
After trying to create a minimal example I realized I was calling the function without the neighbor list.

**Comment by sschoenholz** [comment]
Great! Don't hesitate to post another issue if you run into any trouble.
