### ISSUE TITLE
JAX-md Renderer: possible to slow down frame rate?

### ISSUE THREAD

**Issue by AlmaDalco** [google/jax-md#139]
The JAX-md renderer is great but plays the simulation at a high frame rate. Is it possible to make the frame rate customizable?

Thanks!

Alma

**Comment by sschoenholz** [comment]
This is a great idea! Sorry I've been a bit slow getting to it. I do expect to add adjustable frame rate this week.

**Comment by AlmaDalco** [comment]
Thanks!
It will be a very much appreciated addition!

**Comment by sschoenholz** [comment]
Going to re-open this issue until I've actually implemented the feature to keep track.

**Comment by AlmaDalco** [comment]
Sure!
Alma

**Comment by sschoenholz** [comment]
Wow, this really fell of my radar! Sorry it took so long. You can now specify an optional `frame_rate` keyword argument to the renderer.
