### ISSUE TITLE
Error in Langevin Dynamics

### ISSUE THREAD

**Issue by LeapSheep** [google/jax-md#145]
Hi! I was looking through the code of `nvt_langevin()` and I believe I have found an error. It looks to me like the inertial terms in the Langevin integrator do not take into account the particle masses.

Line 920 - 924 of `simulate.py`:

```python 
C = dt2 * (F - gamma * V) + sigma * dt32 * (xi + theta)
# ...
V = (f32(1) - dt * gamma) * V + dt_2 * (F_new + F)
```

The expression `(F - gamma * V)` in line 920 has incompatible units and I believe it should read `(F / mass - gamma * V)`. The same is true for the last term in line 924, which should be `dt_2 * (F_new + F) / mass`.
I suspect these divisions are not there because the [cited reference](http://itf.fys.kuleuven.be/~enrico/Teaching/molecular_dynamics_2015.pdf) (p. 21) writes these formulas using a variable $f(r) = F(r)/m$ and the masses don't show up explicitly there.

Here is some code to show that changing the particle masses has no effect on simulation trajectories when `kT = 0` and `gamma = 0`,  i.e. when`nvt_langevin()` should reduce to a velocity verlet integrator.

```python
import jax
import jax.numpy as np
from jax_md import space, energy, simulate

disp, shift = space.free()
energy = energy.lennard_jones_pair(disp)

key = jax.random.PRNGKey(0)
sim_key, pos_key = jax.random.split(key, 2)
R = np.array([[i, j] for i in range(5) for j in range(5)])
R += 0.1*jax.random.normal(pos_key, shape=R.shape)
xs = np.arange(1000)

init, apply = simulate.nvt_langevin(
    energy, shift, dt=1e-2, kT=0., gamma=0.)

init_state_m1 = init(sim_key, R, mass=1.)
init_state_m2 = init(sim_key, R, mass=10.)

do_step = jax.jit(lambda s, t: (apply(s), s.position))
_, trajectory_m1 = jax.lax.scan(do_step, init=init_state_m1, xs=xs)
_, trajectory_m2 = jax.lax.scan(do_step, init=init_state_m2, xs=xs)

print('trajectories identical? ', np.allclose(trajectory_m1, trajectory_m2))
```

Thanks and I hope I didn't miss anything simple!

**Comment by sschoenholz** [comment]
Thanks a lot for catching this error and for the clear explanation! You might be the first person to use non-unit masses with Langevin dynamics. I missed this because our tests for the Langevin simulation environment were too simple and the error manifested as a rescaling of the force. In 368a33f4400c4d4299c42aab7c9a9d5ffb28aba9 I fixed the bug and added a test comparing Langevin dynamics to the analytic solution for the case of a harmonic potential to catch any future regressions.

**Comment by LeapSheep** [comment]
Thanks a lot for the quick fix!
