### ISSUE TITLE
feature request: Energy calculation which depends on position & dR

### ISSUE THREAD

**Issue by Roy-Kid** [google/jax-md#148]
Hi, I need to calculate the atom charge with multipole expansion. The spherical harmonics to the cartesian and local frame to global conversion need positions of each pair. Is there any possible to construct a lj_neighor_list-like wrapper and use it in a simulation?  I note that `fn_map` only take `dR` from `nvt_nose_hoover` or other thermostat.

Thanks in advance if you can add this feature, or if it is not necessary we can do it later by ourselves.

**Comment by sschoenholz** [comment]
Hey! Just checking whether you meant to close this issue. Did you figure it out? If not let me know and I'm happy to iterate. At a high level, though, I would write an energy function that takes raw positions, R, and then also computes dR using `space.map_product(displacement_fn)` or `space.map_neighbors(displacement_fn)` with and without neighbor lists respectively. If you are stuck, perhaps you could provide a snippet of what you're hoping to get and I could help get it working.

**Comment by Roy-Kid** [comment]
Hi! I am so sorry that I may misclick the close commit. I rewrite a `pair_neighbor_list` to access positions from the neighbor list and it seems work.  Your code is brilliant and I learn a lot from it. Thank you! When you update `map_product` I will migrant my toy code to it.
