### ISSUE TITLE
use int32 in partition.py

### ISSUE THREAD

**Issue by pmarks** [google/jax-md#159]
I'm wondering if there's any reason that the cell list library in `partition.py` is using `int64` for particle and cell indexes.  Are there practical uses of the tool with more than 2^31 particles / cells?  

Would you be interested in a PR to convert these to `int32`?

**Comment by sschoenholz** [comment]
Great point! I think we would almost certainly be safe to convert the code to int32. If you wanted to put together a PR that would be fantastic.
