### ISSUE TITLE
How can I contribute to the JAX: bond-order potential model?

### ISSUE THREAD

**Issue by SangHyukYoo** [google/jax-md#162]
Hi. I'm SangHyuk Yoo

Thanks for this amazing library.
I am a new user of the JAX library, so I'm not sure how to contribute to the JAX.

Especially, I want to implement bond-order type potential(BOP) models.
I already have a python-based BOP model, and I want to convert it to JAX-MD library format.

Is it okay to fork the JAX-MD and make a pull request after implementing?
If I cannot, please let me know how I can contribute.

Sincerely,
SangHyuk Yoo

**Comment by sschoenholz** [comment]
Hi SangHyuk Yoo,

Thanks for reaching out and for your interest in contributing to JAX MD! We love community contributions. Do you have a paper that describes the potential? In general, if the potential is used in the literature we'd be happy to take contributions. If you submit a pull request let me know and I'll review it and merge.

All the best,
Sam

**Comment by SangHyukYoo** [comment]
Hi. Sam.

This is the original paper that I want to implement. (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.37.6991)
This one is usually called 'Tersoff model'.  When I finished the tests, I will make a pull request.

Are there rules that I have to follow when I develop the module?

Sincerely,
SangHyuk Yoo

**Comment by sschoenholz** [comment]
Awesome! We really like the Tersoff potential. Thanks a a lot for the contribution, if we can help out at all don't hesitate to let us know.

At the moment, all of our potentials are stored in `energy.py` although some primitive operations are contained elsewhere (neural network primitives are in `nn.py`, for example). If there's not too much code, I think it would be nice to keep everything in `energy.py` and tests in `energy_test.py`. However, helper code to compute generic bond order parameters could also go into `quantity.py`. 

In general we try to keep code to lines of at most 80 characters and we use spaces around binary operations (so `a + b` rather than `a+b`). Other than that we're pretty relaxed.

I'll add @ekindogus to this thread since he's a bit more familiar and might be able to say something about what kinds of tests we'd like to have?

**Comment by SangHyukYoo** [comment]
Thanks for your kind reply. I will try to make code with your recommendations.

And @ekindogus have some recommendations for me, please freely contact me.

**Comment by SangHyukYoo** [comment]
I have trouble computing cosine values between two vectors and constructing neighbor list during implementation. Here is the problem.

1. When I use neighbor list with a diamond cubic silicon structure, neighbor list shows that each atom has 5 neighboring atoms. And the index of the last neighbor atoms is always the last index of the atom lists, though the distance is larger than the cutoff distance of 3.2 Angstrom. But in my manual calculation, each atom has 4 neighboring atoms. Did I use wrong way to construct neighbor list?

>     lattice_vectors = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]], 
>       dtype=dtype) * f32(5.431)
>     atoms = np.array(
>       [[0.00, 0.00, 0.00],
>        [0.25, 0.25, 0.25],
>        [0.00, 0.50, 0.50],
>        [0.25, 0.75, 0.75],
>        [0.50, 0.00, 0.50],
>        [0.75, 0.25, 0.75],
>        [0.50, 0.50, 0.00],
>        [0.75, 0.75, 0.25]], dtype=dtype)
>     atoms = lattice(atoms, 2, lattice_vectors)
>     lattice_vectors *= 2
>     displacement, shift = space.periodic_general(lattice_vectors)
>     box_size = np.linalg.det(lattice_vectors) ** (1 / 3)
>     neighbor_fn = partition.neighbor_list(displacement,
>                                         box_size,
>                                         3.2,
>                                         dr_threshold=0.5,
>                                         format=partition.Dense)
>     nbrs = neighbor_fn.allocate(atoms)

2. When I try to compute cosine values without vectorization mapping(vmap), JAX numpy gives me an error like below. How can I resolve this problem? (dR_12 and dR_13 are identical.)

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/shyoo/Codes/python/jax-md/jax_md/quantity.py", line 153, in cosine_angle_between_two_vectors
>     cos_angle = jnp.dot(dR_12, dR_13) / dr_12 / dr_13
>   File "/usr/local/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 4799, in dot
>     return lax.dot_general(a, b, (contract_dims, batch_dims), precision)
> TypeError: dot_general requires contracting dimensions to have the same shape, got [3] and [5].
