### ISSUE TITLE
help to use partition.neighbor_list

### ISSUE THREAD

**Issue by mariogeiger** [google/jax-md#165]
First time I try to use `jax-md`. 

```python
import jax
import jax.numpy as jnp
from jax_md import partition, space

jax.config.update("jax_enable_x64", True)

(displacement_fn, shift_fn) = space.free()

box_size = 100.0
r_cutoff = 3.0
dr_threshold = 0.0

neighbor_list_fn = partition.neighbor_list(
    displacement_fn, 
    box_size=box_size, 
    r_cutoff=r_cutoff, 
    dr_threshold=dr_threshold, 
)

# all far from eachother
R = jnp.array(
    [
        [20.0, 20.0],
        [30.0, 30.0],
        [40.0, 40.0],
        [50.0, 50.0],
    ]
)
neighbors = neighbor_list_fn.allocate(R)
print(neighbors.idx)

# two first point are close to eachother
R = jnp.array(
    [
        [20.0, 20.0],
        [20.0, 20.0],
        [40.0, 40.0],
        [50.0, 50.0],
    ]
)

neighbors = neighbors.update(R)
print(neighbors.idx) 
print(neighbors.did_buffer_overflow)
```

Prints
```
[]
[]
False
```

I expected to see a `True` for `did_buffer_overflow`. 
What do I do wrong?

**Comment by sschoenholz** [comment]
Hey Mario! Really happy that you're checking out jax md. Actually, you're using neighbor lists correctly and you've just stumbled upon a bug. Fortunately, I had actually been working on fixing the bug over the past few days.

Briefly, neighbor lists used to check for overflows when the maximum number of neighbors exceeded the capacity of the neighbor lists. However, neighbor lists use cell lists in an intermediate step and it was possible for the cell list to overflow silently. I added an overflow check to the cell lists and propagate the overflow to the neighbor list. This solves the issue you are seeing here and the neighbor list now correctly identifies that it has overflowed. Incidentally, I also added the repro you provided as a test case.

As soon as the CI passes I'll check in the PR and upload a new version.

Please don't hesitate to let us know if anything isn't working as well as it ought to or if you run into any other issues!

All the best,
Sam

**Comment by sschoenholz** [comment]
Incidentally, you can confirm that this is the issue by setting `disable_cell_list=True` in the `neighbor_list` function.

**Comment by mariogeiger** [comment]
Thanks Sam
