### ISSUE TITLE
Neighbour list missing an entry when sparse and cell list enabled

### ISSUE THREAD

**Issue by oliverdutton** [google/jax-md#168]
I have found a particular pair is missing from my neighbour list when I have the cell list enabled. Just one. Turning off the cell list and everything functions fine.

This is true for Sparse (and OrderedSparse) representation of the neighbour list. For Dense the pair is not missing.

To me, this suggests the indexing is out by 1 somewhere. Maybe a < where it should be <= or 1-indexing being left around with 0-indexing.

https://github.com/oliverdutton/jax-md/blob/cell_list_issue/Cell_list_issue.ipynb

**Comment by sschoenholz** [comment]
Oh, thanks a lot for uncovering this issue and for the super clear repro! I'm looking into it now. I'll hopefully have some answers this evening.

**Comment by sschoenholz** [comment]
Ok! I looked into this issue and I think there is actually no error, but perhaps the documentation and guardrails can be improved. I'll submit a fix later this week improving things in this area.

At the moment, cell lists partition the space [0, L]^d (aka the cube of side-length L). In the data you provided, positions are negative. This invalidates the use of cell lists, but we currently don't mention it in any documentation and we don't have any guards to detect when this happens so I think your attempted usage was very reasonable! If you try pre-processing the data by setting `xyz += jnp.min(xyz)` you should find that the neighbor list contains the correct pair in all cases.

I also noticed that you didn't quite have the right semantics for checking whether a pair of neighbors is in the neighbor list; perhaps I should add a helper function for this. For the record, here is the correct code
```python
def contains_neighbor(nbrs, id_a, id_b):
  if nbrs.format in [partition.Sparse, partition.OrderedSparse]:
    subset0 = nbrs.idx[0, nbrs.idx[1] == id_a]
    subset1 = nbrs.idx[1, nbrs.idx[0] == id_a]
    nbr_present = id_b in subset0 or id_b in subset1
  else:
    nbrs_subset = nbrs.idx[id_a]
    nbr_present = jnp.any(nbrs_subset == id_b)
  return nbr_present
```
Let me know if you have any questions about why this works!

**Comment by oliverdutton** [comment]
Ah, that does explain it. Thank you.

I just saw that I'd specific `wrapped=False` in the space displacement function and assumed that would take care of details like this. 
```python
displacement_fn_periodic, shift_fn_periodic = space.periodic(box_size, wrapped=True)
```

But I see how that information wouldn't be passed to the neighbor list.

The solution should be `xyz -= jnp.min(xyz)` not `+`. This doesn't keep the semantics of checking for particle movements very easily as xyz's from different frames would have different centres. But as a check it works and shows that was indeed the issue.

I've added a periodic wrap on xyz, (and consequently removed the wrapped=True call from the displacement function).
```python
displacement_fn_periodic, shift_fn_periodic = space.periodic(box_size, wrapped=False)
...
def wrap(xyz, box_size):
    return xyz - jnp.floor(xyz/box_size)*box_size
...
nbrs = neighbor_fn.allocate(wrap(xyz, box_size))
```
This syntax could become standard practice, where the neighbor list has to be aware of the wrapping and apply it internally.

`contains_neighbor` looks like a handy util. I had used a set of frozensets (each length 2) to identify the discrepancy originally, then chucked that other function together.

**Comment by sschoenholz** [comment]
Thanks for the feedback! I think you're correct that the current version of neighbor lists isn't incredibly convenient for systems that don't have periodic boundary conditions. I like your idea of including an option to explicitly wrap. Maybe you could make a new issue outlining this problem so I can keep track of the feature request.
