### ISSUE TITLE
Construct Neighbor/Cell List Failed

### ISSUE THREAD

**Issue by DechinPhy** [google/jax-md#173]
#### The version of jax-md been used
0.1.22

#### My code
```python
import jax.numpy as np
from jax import random
from jax_md import partition
from jax_md import space
from jax.config import config
config.update("jax_enable_x64",True)

N = 1000
spatial_dimension = 3
key = random.PRNGKey(0)
R = random.uniform(key, (N, spatial_dimension), minval=0.0, maxval=1.0)
cell_size = 5.0
capacity = 10
box_size = 25.0
cell_list_fn = partition.cell_list(box_size, cell_size, capacity)
cell_list_data = cell_list_fn(R)
displacement_fn, shift_fn = space.periodic(box_size)
neighbor_list_fn = partition.neighbor_list(displacement_fn, box_size, cell_size)
neighbors = neighbor_list_fn.allocate(R)

print (neighbors)
```

#### Error message
```bash
Traceback (most recent call last):
  File "jax_md_benchmarking.py", line 16, in <module>
    cell_list_data = cell_list_fn(R)
TypeError: 'CellListFns' object is not callable
```

**Comment by sschoenholz** [comment]
Hey, thanks for the report. I think you must be one of the only people using `partition.cell_list` directly! The calling convention changed slightly in version 0.1.22 to better match neighbor lists. The syntax is now,
```
cell_list_fn = partition.cell_list(box_size, cell_size, capacity)
# Cell list allocation cannot be JIT.
cell_list = cell_list_fn.allocate(R)
# Cell list update can be JIT.
cell_list = cell_list.update(R)
```

**Comment by DechinPhy** [comment]
> Hey, thanks for the report. I think you must be one of the only people using `partition.cell_list` directly! The calling convention changed slightly in version 0.1.22 to better match neighbor lists. The syntax is now,
> 
> ```python
> cell_list_fn = partition.cell_list(box_size, cell_size, capacity)
> # Cell list allocation cannot be JIT.
> cell_list = cell_list_fn.allocate(R)
> # Cell list update can be JIT.
> cell_list = cell_list.update(R)
> ```

Thank you for replying! There are new problems after I change the code to:
```python
import jax.numpy as np
from jax import random
from jax_md import partition
from jax_md import space
from jax.config import config
config.update("jax_enable_x64",True)

N = 1000
spatial_dimension = 3
key = random.PRNGKey(0)
R = random.uniform(key, (N, spatial_dimension), minval=0.0, maxval=1.0)
cell_size = 5.0
capacity = 10
box_size = 25.0

cell_list_fn = partition.cell_list(box_size, cell_size, capacity)
cell_list = cell_list_fn.allocate(R)
cell_list = cell_list.update(R)
displacement_fn, shift_fn = space.periodic(box_size)
neighbor_list_fn = partition.neighbor_list(displacement_fn, box_size, cell_size)
neighbors = neighbor_list_fn.allocate(R)

print (neighbors)
```
And the running result is:
```bash
Traceback (most recent call last):
  File "jax_md_benchmarking.py", line 25, in <module>
    neighbor_list_fn = partition.neighbor_list(displacement_fn, box_size, cell_size)
TypeError: neighbor_list() missing 1 required positional argument: 'dr_threshold'
```
I'm just running the simple cases in README.

**Comment by sschoenholz** [comment]
Ah, I should change the README. Thanks for catching this. The code following code should work:

```python
import jax.numpy as np
from jax import random
from jax_md import partition
from jax_md import space
from jax.config import config
config.update("jax_enable_x64",True)

N = 1000
spatial_dimension = 3
key = random.PRNGKey(0)
R = random.uniform(key, (N, spatial_dimension), minval=0.0, maxval=1.0)
cell_size = 5.0
capacity = 10
box_size = 25.0

cell_list_fn = partition.cell_list(box_size, cell_size, capacity)
cell_list = cell_list_fn.allocate(R)
displacement_fn, shift_fn = space.periodic(box_size)
neighbor_list_fn = partition.neighbor_list(displacement_fn, box_size, cell_size, dr_threshold=0.0)
neighbors = neighbor_list_fn.allocate(R)

print (neighbors)
```
Note that neighbors are assigned if they are within `cell_size + dr_threshold`. This way you only have to update the neighbor list if a particle has moved more than `dr_threshold / 2` which can be useful if you are running simulations that evolve dynamically.

**Comment by DechinPhy** [comment]
> 



> Ah, I should change the README. Thanks for catching this. The code following code should work:
> 
> ```python
> import jax.numpy as np
> from jax import random
> from jax_md import partition
> from jax_md import space
> from jax.config import config
> config.update("jax_enable_x64",True)
> 
> N = 1000
> spatial_dimension = 3
> key = random.PRNGKey(0)
> R = random.uniform(key, (N, spatial_dimension), minval=0.0, maxval=1.0)
> cell_size = 5.0
> capacity = 10
> box_size = 25.0
> 
> cell_list_fn = partition.cell_list(box_size, cell_size, capacity)
> cell_list = cell_list_fn.allocate(R)
> displacement_fn, shift_fn = space.periodic(box_size)
> neighbor_list_fn = partition.neighbor_list(displacement_fn, box_size, cell_size, dr_threshold=0.0)
> neighbors = neighbor_list_fn.allocate(R)
> 
> print (neighbors)
> ```
> 
> Note that neighbors are assigned if they are within `cell_size + dr_threshold`. This way you only have to update the neighbor list if a particle has moved more than `dr_threshold / 2` which can be useful if you are running simulations that evolve dynamically.

Get it. Thank you very much!
