### ISSUE TITLE
partition.py and quantity.py mutually import each other at the top level

### ISSUE THREAD

**Issue by sabercrombie** [google/jax-md#180]
Importing partition.py results in this error:

   from jax_md import partition
 File "partition.py", line 38, in <module>
    from jax_md import quantity, space, dataclasses, util
 File "quantity.py", line 294, in <module>
    format: partition.NeighborListFormat=partition.Dense):
AttributeError: module 'jax_md.partition' has no attribute 'Dense'

I think this is because quantity.py is importing partition.py, but since it's already been imported the setup of Dense, etc. hasn't happened.  Importing at the function level might help?

**Comment by sschoenholz** [comment]
Thanks for reporting this! I removed the import to quantity from partition.py. Seems to fix the issue on my end, but let me know if something is still amiss.

**Comment by sabercrombie** [comment]
Works for me.
