### ISSUE TITLE
Neighbor and cell list bugs

### ISSUE THREAD

**Issue by S-Thaler** [google/jax-md#191]
Hi,
we recently encountered a few bugs with the neighbor list. The first one is concerned with cell list construction with fractional coordinates, if the box is provided as a [ndim] vector.

```python
import jax.numpy as jnp
from jax_md import space, partition

box_vector = jnp.ones(3) * 3
box_tensor = jnp.eye(3) * 3

r_cut = 0.1
_positions = jnp.linspace(0.5, 0.7, 20)
positions = jnp.stack([_positions, _positions, _positions], axis=1)

# periodic_general seems to work with box scalar, array and tensor, even though
# documentation mentions only tensor
displacement, _ = space.periodic_general(box_tensor,
                                         fractional_coordinates=True)

# works, even though box_tensor is not mentioned in docs
neighbor_fn = partition.neighbor_list(displacement, box_tensor, r_cut,
                                      0.1 * r_cut, fractional_coordinates=True)

# fails due to issue in cell_list
# neighbor_fn = partition.neighbor_list(displacement, box_vector, r_cut,
#                                       0.1 * r_cut, fractional_coordinates=True)

# works
# neighbor_fn = partition.neighbor_list(displacement, box_vector, r_cut,
#                                       0.1 * r_cut, fractional_coordinates=True,
#                                       disable_cell_list=True)

nbrs = neighbor_fn.allocate(positions)
```

The other bugs are somewhat slippery and are related to the (admittedly off-design) case where the neighborlist is "full", either from all particles being connected or from choosing a too large capacity multiplier. In this case, the neighborlist.idx is capped at [n_particles, n_particles], even though [n_particles, n_particles - 1] seems more natural since this is the maximum size in the default case, where the "own" particle is excluded. The code then fails if nbrs.update tries to allocate a [n_particles, n_particles - 1] list. Additionally, if the capacity multiplier is set to 1, the neighborlist incorrectly indicates overflow straight from allocation, because capacity = max_capacity, irrespective if the neighborlist is "full".

```python
import jax.numpy as jnp
from jax_md import space, partition

# cases:
# r_cut = 0.25, disable_cell_list = False, capacity_multiplier = 1.5:
#     allocates nbrs.idx (20, 20) -> would expect (20, 19) as same particle is
#     not included by default, but works as nbrs.update also allocates (20, 20)
# r_cut = 0.31, disable_cell_list = False, capacity_multiplier = 1.5:
#     Fails, as nbrs.update tries to allocate (20, 19)
# r_cut = 0.31, disable_cell_list = False, capacity_multiplier = 1.:
#     Works, as initially allocates nbrs.idx correctly to (20, 19),
#     but incorrectly sets overflow to True because it tests for
#     capacity >= max_capacity, which is always true for a "full" neighborlist.
#     This overflow issue therefore also arises if not all particles are
#     connected, e.g. r_cut = 0.1.
# disable_cell_list = True, capacity_multiplier = 1.5:
#     Fails for all cases, where the neighbor list is allocated (20, 20)
#     (i.e. r_cut >= 0.12), because nbrs.update tries to allocate (20, 19)
r_cut = 0.12
disable_cell_list = True
capacity_multiplier = 1.5

box = jnp.ones(3)
_positions = jnp.linspace(0.5, 0.7, 20)
positions = jnp.stack([_positions, _positions, _positions], axis=1)
print('Atom shapes:', positions.shape)
displacement, _ = space.periodic(box)

neighbor_fn = partition.neighbor_list(displacement, box, r_cut, 0.1 * r_cut,
                                      capacity_multiplier=capacity_multiplier,
                                      disable_cell_list=disable_cell_list)
nbrs = neighbor_fn.allocate(positions)

print('Neighbor overflow after initial allocation:', nbrs.did_buffer_overflow)
print('Initial neighbor list shape:', nbrs.idx.shape)
new_nbrs = nbrs.update(positions)
print('Neighbor list shape after update:', new_nbrs.idx.shape)
print('Neighbor overflow after update:', new_nbrs.did_buffer_overflow)
```

**Comment by sschoenholz** [comment]
Thanks for pushing on these corner cases of neighbor lists / cell lists! I think I have fixed the issues and added some regression tests, but let me know if anything still seems off. 

I will say that the box tensor case works, but I think it might be mostly to do with this specific setting. For example, if you used a box that had significant off-diagonal components (so that it wasn't rectangular) then I think the cell size would be incorrect. I am considering making it an error to pass a tensor box, what do you think?

**Comment by S-Thaler** [comment]
Thanks for the quick fixes, now this seems to work in our examples.

I agree, it seems prudent to throw an error if the cell list can be incorrect for boxes with significant off-diagonal components, which is usually the case if the user passes a box tensor in combination with fractional coordinates. 

However, does this mean that neighbor lists might also be incorrect for non-rectangular boxes, even if cell lists are disabled? If not, I would only throw an error if a box tensor is passed with disable_cell_list = False as neighbor lists still seem very useful for the non-rectangular box case.

**Comment by sschoenholz** [comment]
Yeah, this would only be for when using cell lists. Actually, your comment made me realize that the `box` argument is unused when cell lists are disabled. Maybe I should get rid of the `disable_cell_list` argument altogether and infer whether we use cell lists from whether or not there is a box...

**Comment by S-Thaler** [comment]
That seems reasonable and might also make the link between rectangular boxes and cell lists more transparent to users. Thanks for looking into this!
