### ISSUE TITLE
Too deformed in periodic_general boundary conditions

### ISSUE THREAD

**Issue by S-Roecken** [google/jax-md#200]
Hi,

In the periodic_general boundary conditions it states:  

"It will also fail to find the correct image when the box is too deformed. We hope to add a
more robust box for small simulations soon (TODO) along with better error
checking. In the meantime caution is recommended."

Is there a measure of "too deformed", e.g. a certain angle of the box vectors, that imply that a box is too deformed? 

Thank you for this great library and the time you put into this!

Best
Sebastien

**Comment by sschoenholz** [comment]
Great question! Actually, although the "soon" in the comment is clearly a lie, I have been working on making this more robust lately. The main issue is that jax md uses minimum image convention, which means that each atom can only "see" its nearest periodic image. However, if you are using an interatomic potential with a cutoff, $l_c$,  for square boxes that are smaller than $l_c / 2$ or deformed boxes where the smallest distances across the box is less than $l_c / 2$ the atoms will interact with copies of themselves further than one image away. In practice, therefore, one really should include all possible interacting pairs. LAMMPS, for example, does this by considering ghost particles which can be many periodic images away. To be honest, I think this is one case where there is a bit of friction between JAX MD's functional nature and the code we'd like to implement. However, I think I'm converging on a decent solution.

**Comment by S-Roecken** [comment]
Thank you for the detailed answer!
