### ISSUE TITLE
Nothing shown in the renderer

### ISSUE THREAD

**Issue by RodenLuo** [google/jax-md#205]
Hi, I'm following [JAX MD: A Framework for Differentiable Atomistic Physics](https://youtu.be/iqf8LcT17_0?t=1805). 

I'm expecting this image: 

![image](https://user-images.githubusercontent.com/8460424/179382928-9ed7e620-dc53-44cb-b18b-672ce1caa483.png)

But I only get the black background: 

![image](https://user-images.githubusercontent.com/8460424/179382900-71f43118-f3ca-4510-a9a3-5a782f053d6b.png)

This also happens to all the render results in the rest of the cells. Any help is much appreciated.

**Comment by sschoenholz** [comment]
Thanks for bringing this up! There was an upstream JAX change that required us to fix the renderer. It was already fixed at head, but a new PyPi release hadn't been packaged since the fix. Now everything should work properly, but please let me know if anything is still broken.

**Comment by RodenLuo** [comment]
Yes, it's fixed now. Thanks!
