### ISSUE TITLE
The value of n_pos in Fire_Descent

### ISSUE THREAD

**Issue by leeyang** [google/jax-md#24]
Hi,

 Should n_pos be reset to 0 when P < 0? Like 
`n_pos= np.where(P < 0, 0, n_pos)`
after Line 160 in minimize.py?

**Comment by sschoenholz** [comment]
Thanks for bringing this up! I think it probably suffices to change L156 to `n_pos = np.where(P > 0, n_pos + f32(1.0), f32(0))`. I'll submit the fix shortly.
