### ISSUE TITLE
Storing intermediate states on disk efficiently

### ISSUE THREAD

**Issue by marekjg** [google/jax-md#30]

**Comment by sschoenholz** [comment]
Hey! Thanks for your question. Do you mind elaborating on exactly what the use case is? Generally, I just use np.save() to save arrays of positions. However, perhaps you mean something more?

**Comment by marekjg** [comment]
Hi, sorry, I've written description but then thought whether I should ask this question here or maybe on jax and probably miss clicked something. What I mean is that I want to perform simulation and while doing that, store intermediate states on disk without impact on the performance of the simulation. If the function with the loop of the simulation is jit compiled, wouldn't np.save hang the computation or maybe impact the jit? Thanks for the answer anyway and sorry for no description.

**Comment by sschoenholz** [comment]
Ah I see, great question! Yes, you're totally right that np.save won't work within a jit block. Overall there are (at least) two strategies that you could try out. 

The easiest way to proceed is to jit some number of steps of computation and then save states in between. This will be slightly less efficient, but it's possible you won't really notice a difference (JAX / XLA use async dispatch to hide a lot of the python latency).

Another approach (that we are actually thinking about formalizing in some way) is to have a buffer of positions as a tuple of an ndarray of shape `[buffer_size, N, spatial dimension]` and an index `i` specifying the current location in the buffer. Then you can use a function (untested) like,
```python
def push_positions(buffer_state, position):
  buffer, i = buffer_state
  buffer = ops.index_update(buffer, ops.index[i, :, :], position)
  i = i + 1
  return (buffer, i)
```
to add a position to the buffer. This would allow you to jit compile enough steps to fill your buffer and then you could write it out as a single call to np.save.

Let me know if this makes sense, or if you need any help with implementation details. It is also possible that there are other approaches that we haven't thought about yet. FWIW, I think that formalizing some of these ideas down the road could lead to ways to catch errors in jit compiled code (e.g. singular transformation matrices or convergence in FIRE optimization etc...)

**Comment by marekjg** [comment]
Thanks for clearing things up, it makes perfect sense, I'll try the second approach as it seems compelling
