### ISSUE TITLE
error: GPU memory usage is close to the limit

### ISSUE THREAD

**Issue by cpgoodri** [google/jax-md#4]
To reproduce the problem:
1. Runtime: reset all runtimes
2. run:
```
!pip install --upgrade -q https://storage.googleapis.com/jax-wheels/cuda$(echo $CUDA_VERSION | sed -e 's/\.//' -e 's/\..*//')/jaxlib-0.1.15-cp36-none-linux_x86_64.whl
!pip install --upgrade -q jax
!pip install -q `git+https://www.github.com/google/jax-md

import numpy as onp
import jax.numpy as np
from jax import random
from jax import jit, grad
from jax.config import config
config.update("jax_enable_x64", True)
from jax_md import space, smap, energy, minimize, quantity, simulate`

def SetPositionsOctahedron():
  a=1/np.sqrt(2.)
  R=list(np.full((6,3),0.))
  R[0]=np.array([a,0,0])
  R[1]=np.array([-a,0,0])
  R[2]=np.array([0,a,0])
  R[3]=np.array([0,-a,0])
  R[4]=np.array([0,0,a])
  R[5]=np.array([0,0,-a])
  return np.array(R).astype(np.float64)
```

At this point, everything is fine, but if you then run:

```
box_size = 8.
Rinit = SetPositionsOctahedron()+box_size/2
```

you get the following error message:

> GPU memory usage is close to the limit
> Your GPU is close to its memory limit. You will not be able to use any additional memory in this session. Currently, 10.07 GB / 11.17 GB is being used. Would you like to terminate some sessions in order to free up GPU memory (state will be lost for those sessions)?

If I press "ignore," the issue doesn't go away but it doesn't seem to negatively affect me. That might be because I'm not (yet) running computationally intensive work. So the good news I don't need this fixed in order to keep working (for now), but I thought you should be away of it.

**Comment by sschoenholz** [comment]
Hey! Thanks for raising this. My belief is that JAX allocates 90% of GPU memory upfront to improve performance during execution, so this is expected behavior. If you see crashes and actual OOM, please don't hesitate to raise it here.
