### ISSUE TITLE
scaling typo

### ISSUE THREAD

**Issue by khegazy** [google/jax-md#48]
In the bubble tutorial in pair_correlation_fun

dr = np.where(dr > 1e-7, dr, 1e7)

I believe the last number should be 1e-7

**Comment by sschoenholz** [comment]
Thanks for raising this! This line of code is actually there to stop the pair correlation function from counting the central particle. By setting dr to 1e7 we ensure that g(dr) = 0 and so those particles will get removed from the calculation. Another reasonable approach to this problem would be to compute g(dr) and then multiply by a mask e.g. `(1 - np.eye(dr.shape[0]))`. 

As a note, one reason why we went with this approach vs the mask approach is that in some cases, e.g. the LJ potential, when f(dr) \to\infty as dr\to0 then the masking approach can pollute gradients with nans. See, e.g. https://github.com/google/jax/issues/1052. However, that is not an issue in this case so either approach would be fine!
