### ISSUE TITLE
energy.soft_sphere radii vs diameter

### ISSUE THREAD

**Issue by khegazy** [google/jax-md#49]
Line 75-76 in jax-md/jax_md/energy.py 

Here dr is normalized so a value of 1 means they are one radius away. Therefore, your function is only non-zero if two bubbles are less than one radius apart (1), however, the bubbles begin to touch when they are 2 radii apart (2). Thus, your function is only nonzero after the bubbles are compressed halfway.

**Comment by sschoenholz** [comment]
Thanks for raising this. We do indeed specify diameters rather than radii which is standard. However, as you notice our documentation is wrong. Thanks for pointing it out!
