### ISSUE TITLE
Feature request: Potential truncation and smoothing

### ISSUE THREAD

**Issue by cpgoodri** [google/jax-md#5]
This is really easy to do by hand, but might be nice to have it automatically built in as an option somehow.

Basically, whenever there is a pair interaction that doesn't have strict cutoff, it is common to truncate it as some finite distance r_cut. However, you then get a small discontinuity in the potential at r_cut, so it is common to adjust the potential slightly so that it is C1 (continuous in the potential and first derivative). The best way I've seen this does is the '[xplor' mode in HOOMD Blue ](https://hoomd-blue.readthedocs.io/en/stable/module-md-pair.html#hoomd.md.pair.pair) where you have a smoothing function S(r) that satisfies the following:

- S(r) = 1 when r< ron
- S(r) = 0 when r> rcut
- S(r) is C1 everywhere

You then just multiply your potential by S(r) and choose ron and rcut to be in the tail of the potential.

**Comment by sschoenholz** [comment]
Added a first version of this in #20. For an example of use, see the `lennard_jones_pairwise` function. I'm open to adding other versions of truncation down the road, if anyone ever wants them.
