### ISSUE TITLE
Feature request: energy.isotropic function

### ISSUE THREAD

**Issue by cpgoodri** [google/jax-md#56]
The function energy.multiplicative_isotropic_cutoff creates the need for potentials like soft_sphere take an (N,N) array of distances rather than an (N,N,d) array of displacements. However, smap.pair, among others, still need a function that takes (N,N,d) arrays of displacements. In the solution I just proposed to #55, energy.multiplicative_isotropic_cutoff serves this purposes of calling space.distance(dR) and passing the result to the wrapped energy function. I propose a similar function, lets call it energy.isotropic, whose only purpose is to call space.distance(dR). This would increase code reusability, for example:
```
def my_potential(dr, **kwargs):
  ...

def my_potential_pair(metric):
  return smap.pair(
      energy.isotropic(my_potential),
      metric)

def my_potential_pair_cutoff(metric, r_onset, r_cutoff):
  return smap.pair(
      energy.multiplicative_isotropic_cutoff(my_potential, r_onset, r_cutoff),
      metric)
```

**Comment by sschoenholz** [comment]
I think we resolved this offline, do you mind if I close the issue?
