### ISSUE TITLE
ImportError: cannot import name 'custom_jvp'

### ISSUE THREAD

**Issue by williamdjones** [google/jax-md#91]
I've followed the instructions for the pip install as well as pip install'ing from the most recent clone of the repo. In both cases, I double check that I'm not inside of the jax_md dir on my system. So I follow the space.py instructions and I get the following error:

```
>>> from jax_md import space
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/workspace/wsa/jones289/miniconda3/envs/jaxmd/lib/python3.5/site-packages/jax_md/__init__.py", line 15, in <module>
    from jax_md import space
  File "/usr/workspace/wsa/jones289/miniconda3/envs/jaxmd/lib/python3.5/site-packages/jax_md/space.py", line 41, in <module>
    from jax import custom_jvp
ImportError: cannot import name 'custom_jvp'
```

I tried previously with python 3.7, so I tried reinstalling with python=3.5, but that doesn't seem to be the issue. I'm not sure if I misread the documentation on how to setup jax_md but clearly something is wrong here.

**Comment by sschoenholz** [comment]
Hey! Thanks for the question. I just tried pip installing (using `pip install jax_md`) in a fresh virtual environment and didn't encounter the issue (using python 3.6.8). Can you check what version of JAX is installed? 

```
import jax
print(jax.__version__)
```

**Comment by williamdjones** [comment]
interesting....I installed using a fresh conda environment with python=3.6.8 and the import works now..okay! Thank you for the help.
