### ISSUE TITLE
nans in MD cookbook notebook

### ISSUE THREAD

**Issue by wfreinhart** [google/jax-md#98]
This seems like a really excellent project and I am excited about the potential for gradient-based optimization with your approach. However, in running the MD cookbook notebook, every simulation or minimization routine results in nans. I was surprised to find this even for simple Lennard-Jones fluid at low density and with very small time steps (it occurs even for 1e-6 sometimes). I am running directly from Google Colab so it doesn't seem like an issue on my end. Is there a stable version I could try rolling back to where this has been tested?

I also tried the `jax.config.update("jax_debug_nans", True)` setting and got the following output from the first Brownian dynamics simulation of the bubble raft _on the first step_:

Invalid value encountered in the output of a jit function. Calling the de-optimized version.

---------------------------------------------------------------------------
FloatingPointError                        Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py in _xla_call_impl(fun, device, backend, name, donated_invars, *args)
    528   try:
--> 529     return compiled_fun(*args)
    530   except FloatingPointError:

21 frames
FloatingPointError: invalid value (nan) encountered in xla_call

During handling of the above exception, another exception occurred:

FloatingPointError                        Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py in _check_nans(name, xla_shape, buf)
    350   if dtypes.issubdtype(xla_shape.element_type(), np.inexact):
    351     if np.any(np.isnan(buf.to_py())):
--> 352       raise FloatingPointError(f"invalid value (nan) encountered in {name}")
    353 
    354 ### compiling jaxprs

FloatingPointError: invalid value (nan) encountered in mul

**Comment by sschoenholz** [comment]
Hi @wfreinhart thanks a lot for your message, sorry you're finding NaNs! I just opened up / ran the JAX MD cookbook and it did not give NaNs (except, curiously for once cell in the NN example because the learning rate is slightly too high). It is strange because, as you suggest, neither of us are running locally and we are both using a fresh install. 

One thing I'm curious about: in the cookbook notebook I don't actually see that we use LJ anywhere, just to confirm: you also observe NaNs with the soft sphere potential?

**Comment by wfreinhart** [comment]
Thanks for the quick reply! Yes, I was talking about the soft sphere potential in the cookbook, sorry for the confusion.

I triple checked and realized my mistake -- I was looking at an old version of the code at https://github.com/jaxmd/jax-md and literally didn't realize until this moment that it was located at a different url than this one. My mistake!

**Comment by sschoenholz** [comment]
Ah yes, this is confusing; that version was an anonymized version for a conference but really it shouldn't exist anymore. I'll make a note to delete it. In case you were looking there, we have a number of new notebooks now that I think are a bit more current than the cookbook notebook!
