### ISSUE TITLE
FireDescentState changing type and causing error

### ISSUE THREAD

**Issue by cpgoodri** [google/jax-md#99]
Some code that was working a few days ago is now throwing an error. I know there have been a lot of changes recently, and I think this is an easy fix (but I'm not 100% sure what the right thing to do is, so I'm filing an issue rather than a PR). 

Without going into the details (I can send code if necessary), I am doing a FIRE minimization using lax.scan, and it appears the type of the FireDescentState is changing. Specifically `n_pos` is changing from an `int64` to a `float32`. My guess is that in line 154 of minimize.py:
```
    return FireDescentState(R, V, force(R, **kwargs), dt_start, alpha_start, 0)  # pytype: disable=wrong-arg-count
``` 
the `0` should be explicitly cast to an `f32`?

Here's the error I'm getting:

```TypeError: scan carry output and input must have identical types, got
FireDescentState(position=ShapedArray(float64[19,7,3]), velocity=ShapedArray(float64[19,7,3]), force=ShapedArray(float64[19,7,3]), dt=ShapedArray(float16[]), alpha=ShapedArray(float16[]), n_pos=ShapedArray(float32[]))
and
FireDescentState(position=ShapedArray(float64[19,7,3]), velocity=ShapedArray(float64[19,7,3]), force=ShapedArray(float64[19,7,3]), dt=ShapedArray(float16[]), alpha=ShapedArray(float16[]), n_pos=ShapedArray(int64[])).
```

**Comment by sschoenholz** [comment]
Thanks for the report, this was fixed in commit 285045e94af8fa0645670e7d07ef68e9702159e8.
